#kjsdcsdhkl
- hosts: all
  become: true
  tasks:
    - copy:
        content: "hello"
        dest: /tmp/dhfdjsjhghdjk.txt
      notify: restart http



  handlers:
     - name: restart http
       service: 
           name: haproxy
           state:  restarted
         



