#kjsdcsdhkl
- hosts: all
  become: true
  tasks:
   - copy:
        content: "hello world"
        dest: /tmp/abc2.txt
     notify: restart  http

  handlers:
   - name: restart  http
     service:
        name: httpd
        state: restarted
